function plot_text(ax, pos, str, color)
    text(ax, pos(1), pos(2), str, ...
        'Units','normalized', ...
        'Interpreter','none', ...
        'VerticalAlignment','bottom', ...
        'HorizontalAlignment','right', ...
        'FontSize',15, ...
        'FontWeight','bold', ...
        'Color','k', ...
        'BackgroundColor',[1 1 1 0.95], ...
        'EdgeColor', color, ...
        'LineWidth', 2, ...
        'Margin',3, ...
        'HandleVisibility','off');
end