function plot_tt(stamp, data, max_opp, color, name, varargin)
    plot(stamp, data(:,1:max_opp), ...
        'Color', color, ...
        'HandleVisibility', 'off', ...
        varargin{:});
    plot(NaN, NaN, ...
        'Color', color, ...
        'DisplayName', name);
end
