function plotArea(t, data, max_opp, color, name)
    area(t, data(:,1:max_opp), ...
        'FaceColor', color, ...
        'EdgeColor', color, ...
        'HandleVisibility','off');
    plot(NaN, NaN, 's', ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', color, ...
        'DisplayName', name);
end
