function cb = create_opponent_checkboxes(parentFig, checklist_strings, default_selection, tag)
    nOpp = numel(checklist_strings);
    base_height_per_opp = 0.05;  
    panel_height = min(base_height_per_opp * nOpp + 0.05, 0.9);  

    panel = uipanel('Parent',parentFig, ...
        'Units', 'normalized', ...
        'Position', [0.02, 0.95 - panel_height, 0.90, panel_height], ...
        'Title','Opponents', ...
        'BorderType','etchedin');

    cb = gobjects(nOpp,1);
    for k = 1:nOpp
        base_height_per_opp = (1 - 0.05) / nOpp;  
        ypos = 1 - (k * base_height_per_opp) - 0.08;  % Top to bottom
        cb(k) = uicontrol('Parent', panel, ...
            'Style', 'checkbox', ...
            'String', checklist_strings{k}, ...
            'Units', 'normalized', ...
            'Position', [0.05, ypos, 0.9, base_height_per_opp], ...
            'Value', ismember(k, default_selection), ...
            'Callback', @(src, evt) update_opponent_selection(src, evt, tag));
    end
end