function lap = fill_with_nan()
    lap.x = NaN;
    lap.y = NaN;
    lap.v = NaN;
    lap.yaw = NaN;
    lap.s = NaN;
    lap.t_vec_filt = NaN;
    lap.x_filt = NaN;
    lap.y_filt = NaN;
    lap.v_filt = NaN;
    lap.yaw_filt = NaN;
    lap.ax = NaN;
    lap.x_smooth = NaN;
    lap.y_smooth = NaN;
    lap.rho_smooth = NaN;
    lap.s_smooth = NaN;
    lap.v_smooth = NaN;
    lap.ax_smooth = NaN;
    lap.ay_smooth = NaN;
end