%% VEHICLE STATUS
if isfield(bag1.log, 'supervisor__vehicle_status')
    figure('Name','Supervisor state');
    tiledlayout(1,1);
    ax(f) = nexttile; f = f+1;
    hold on;
    plot(bag1.sup_time, double(bag1.log.supervisor__vehicle_status.state),'DisplayName','Traj State');
    xlabel("Time [s]")
    yticks(double([VEH_STATUS.IDLE, ...
                   VEH_STATUS.PAUSED, ...
                   VEH_STATUS.FINISH, ...
                   VEH_STATUS.IN_ROW, ...
                   VEH_STATUS.OUT_ROW, ...
                   VEH_STATUS.EXITING, ...
                   VEH_STATUS.ENTERING, ...
                   VEH_STATUS.OBSTACLE_INSIDE, ...
                   VEH_STATUS.ERROR, ...
                   VEH_STATUS.MANUAL]));
    
    yticklabels({'IDLE', ...
                 'PAUSED', ...
                 'FINISH', ...
                 'IN\_ROW', ...
                 'OUT\_ROW', ...
                 'EXITING', ...
                 'ENTERING', ...
                 'OBSTACLE\_INSIDE', ...
                 'ERROR', ...
                 'MANUAL'});
    legend show
end