CURVATURE_RESAMPLE_PARAMS.rho_windowsidelen = 20;
CURVATURE_RESAMPLE_PARAMS.rho_n_filters = 10;
CURVATURE_RESAMPLE_PARAMS.s_windowsidelen = 20;
CURVATURE_RESAMPLE_PARAMS.s_n_filters = 10;
CURVATURE_RESAMPLE_PARAMS.rho_min_threshold = 5e-3;
CURVATURE_RESAMPLE_PARAMS.N_new_points = 1000;

SMOOTHING_TOL = 1.5; % [m];