function plot_covariance_position(time, X, Y, sigma_X, sigma_Y, color)
step = floor(length(time)/1000);
for i=1:25:length(time)
    rectangle("Position", [X(i)-sigma_X(i), Y(i)-sigma_Y(i), 2*sigma_X(i), 2*sigma_Y(i)], ...
              "Curvature", [1 1], ...
              "FaceColor", [color 0.2], ...
              "LineStyle", "none", ...
              "HandleVisibility", "off");
end
end