%% ESTIMATE R RHO_DOT
%
% Stima R_rho_dot per il radar. Produce tre figure:
%   1) Distribuzione senza gating
%   2) Distribuzione con gating in posizione
%   3) Andamento temporale di rho_dot_err

% Prendi il radar dalla struct sensors
radar_idx = find(cellfun(@(s) strcmp(s.id, 'rad_clust'), sensors), 1);
s     = sensors{radar_idx}.s;
col_k = sensors{radar_idx}.col;

if ~isfield(s, 'rho_dot')
    error('rho_dot non trovato nella struct radar.');
end
if ~isfield(s, 'rho_dot_gt')
    error('rho_dot_gt non trovato nella struct radar.');
end

% ----------------------------------------------------------------
% Estrai colonna 1 e calcola errore rispetto al GT
% ----------------------------------------------------------------
rho_dot_col1 = s.rho_dot(:, 1);
rho_dot_gt   = s.rho_dot_gt(:, 1);
sens_stamp   = s.sens_stamp(:);

% Errore in posizione (colonna 1) per il gating
x_rel_err_col1 = s.x_rel_err(:, 1);
y_rel_err_col1 = s.y_rel_err(:, 1);
pos_err        = hypot(x_rel_err_col1, y_rel_err_col1);

valid = ~isnan(rho_dot_col1) & ~isnan(rho_dot_gt) & (rho_dot_gt ~= 0);

e_raw  = rho_dot_col1(valid) - rho_dot_gt(valid);
t_raw  = sens_stamp(valid);
pe_raw = pos_err(valid);   % errore posizione corrispondente

pos_thr = 5.0;  % soglia gating in posizione [m]

%% Stats senza gating — fit gaussiano
pd_raw    = fitdist(e_raw, 'Normal');
mu_raw    = pd_raw.mu;
sigma_raw = pd_raw.sigma;
R_raw     = sigma_raw^2;

%% Stats con gating in posizione — fit gaussiano
ass     = pe_raw < pos_thr;
e_gated = e_raw(ass);
t_gated = t_raw(ass);

pd_gated    = fitdist(e_gated, 'Normal');
mu_gated    = pd_gated.mu;
sigma_gated = pd_gated.sigma;
R_gated     = sigma_gated^2;

fprintf('\n===== R RHO_DOT ESTIMATION =====\n');
fprintf('%-25s  %8s  %8s  %8s  %6s\n', 'Config', 'mu', 'sigma', 'R', 'N');
fprintf('%s\n', repmat('-', 1, 65));
fprintf('%-25s  %8.4f  %8.4f  %8.4f  %6d\n', ...
    'no gate (col 1)', mu_raw, sigma_raw, R_raw, numel(e_raw));
fprintf('%-25s  %8.4f  %8.4f  %8.4f  %6d\n', ...
    sprintf('gate pos < %.0f m', pos_thr), mu_gated, sigma_gated, R_gated, numel(e_gated));
fprintf('%s\n\n', repmat('-', 1, 65));

%% ---- Figura 1: distribuzione senza gating ----
do_plot(e_raw, mu_raw, sigma_raw, R_raw, col_k, ...
    'R rho_dot no gate', ...
    'RADAR  —  \rho_{dot}  —  no gate', ...
    numel(e_raw));

%% ---- Figura 2: distribuzione con gating in posizione ----
do_plot(e_gated, mu_gated, sigma_gated, R_gated, col_k, ...
    sprintf('R rho_dot gate pos %.0f m', pos_thr), ...
    sprintf('RADAR  —  \\rho_{dot}  —  gate pos < %.0f m', pos_thr), ...
    numel(e_gated));

%% ---- Figura 3: andamento temporale ----
do_plot_time(t_raw, e_raw, t_gated, e_gated, ...
    sigma_raw, sigma_gated, pos_thr, col_k);


%% ================================================================
function do_plot(err, mu, sigma, R, col_k, fig_name, fig_title, N)

    scr   = get(0, 'ScreenSize');
    fig_w = 640;
    fig_h = 500;

    figure('Name', fig_name, 'Color', 'w', ...
        'Position', [(scr(3)-fig_w)/2 (scr(4)-fig_h)/2 fig_w fig_h]);

    ax = axes('Position', [0.12 0.11 0.82 0.68]);
    hold(ax, 'on'); grid(ax, 'on'); box(ax, 'on');

    % Istogramma
    histogram(err, 60, ...
        'FaceColor',        col_k, ...
        'FaceAlpha',        0.4,   ...
        'EdgeColor',        'none', ...
        'Normalization',    'pdf', ...
        'HandleVisibility', 'off', ...
        'Parent',           ax);

    % Fit gaussiano
    x_fit   = linspace(mu - 5*sigma, mu + 5*sigma, 400);
    pdf_fit = normpdf(x_fit, mu, sigma);

    plot(ax, x_fit, pdf_fit, '-', ...
        'Color',     col_k, ...
        'LineWidth', 2.5,   ...
        'HandleVisibility', 'off');

    % Linee mu, +sigma, -sigma
    xline(ax, mu, '-', ...
        'Color',                 col_k * 0.7, ...
        'LineWidth',             1.5, ...
        'Label',                 '\mu', ...
        'LabelVerticalAlignment','bottom', ...
        'FontSize',              10, ...
        'Interpreter',           'tex', ...
        'HandleVisibility',      'off');

    xline(ax, mu + sigma, '--', ...
        'Color',                 col_k * 0.7, ...
        'LineWidth',             1.2, ...
        'Label',                 '+\sigma', ...
        'LabelVerticalAlignment','bottom', ...
        'FontSize',              10, ...
        'Interpreter',           'tex', ...
        'HandleVisibility',      'off');

    xline(ax, mu - sigma, '--', ...
        'Color',                 col_k * 0.7, ...
        'LineWidth',             1.2, ...
        'Label',                 '-\sigma', ...
        'LabelVerticalAlignment','bottom', ...
        'FontSize',              10, ...
        'Interpreter',           'tex', ...
        'HandleVisibility',      'off');

    % Rug plot
    pdf_max = max(pdf_fit);
    step    = max(1, floor(numel(err) / 1000));
    plot(ax, err(1:step:end), repmat(-0.03*pdf_max, numel(err(1:step:end)), 1), ...
        '.', 'Color', col_k, 'MarkerSize', 3, 'HandleVisibility', 'off');

    % Limiti assi
    xlim(ax, [mu - 5*sigma,  mu + 5*sigma]);
    ylim(ax, [-0.08*pdf_max,  pdf_max * 1.18]);

    xlabel(ax, '\rho_{dot} error  [m/s]', 'Interpreter', 'tex', 'FontSize', 11);
    ylabel(ax, 'pdf', 'FontSize', 11);

    % Titolo riga 1
    annotation('textbox', [0 0.87 1 0.09], ...
        'String',              sprintf('%s  (N = %d)', fig_title, N), ...
        'Interpreter',         'tex', ...
        'FontSize',            13, ...
        'FontWeight',          'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment',   'middle', ...
        'EdgeColor',           'none', ...
        'FitBoxToText',        'off');

    % Titolo riga 2: statistiche — Interpreter none
    annotation('textbox', [0 0.80 1 0.07], ...
        'String', sprintf('sigma = %.4f m/s     R = %.4f m^2/s^2     mu = %.4f m/s', ...
            sigma, R, mu), ...
        'Interpreter',         'none', ...
        'FontSize',            10, ...
        'FontWeight',          'normal', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment',   'middle', ...
        'EdgeColor',           'none', ...
        'FitBoxToText',        'off', ...
        'Color',               [0.35 0.35 0.35]);

end


%% ================================================================
function do_plot_time(t_all, e_all, t_gated, e_gated, ...
        sigma_raw, sigma_gated, pos_thr, col_k)

    scr   = get(0, 'ScreenSize');
    fig_w = 1100;
    fig_h = 480;

    figure('Name', 'R rho_dot time series', 'Color', 'w', ...
        'Position', [50 (scr(4)-fig_h)/2 fig_w fig_h]);

    ax = axes('Position', [0.07 0.12 0.90 0.70]);
    hold(ax, 'on'); grid(ax, 'on'); box(ax, 'on');

    light_col = 0.45*[1 1 1] + 0.55*col_k;

    % Tutti i campioni
    plot(ax, t_all, e_all, '.', ...
        'Color',      light_col, ...
        'MarkerSize', 3, ...
        'DisplayName', '\rho_{dot} err  (all)');

    % Campioni dopo gating in posizione
    plot(ax, t_gated, e_gated, '.', ...
        'Color',      col_k, ...
        'MarkerSize', 4, ...
        'DisplayName', sprintf('\\rho_{dot} err  (pos err < %.0f m)', pos_thr));

    gray = [0.45 0.45 0.45];
    dark = [0.15 0.15 0.15];

    % ±sigma no gate
    yline(ax,  sigma_raw, '--', 'Color', gray, 'LineWidth', 1.3, ...
        'Label', '+\sigma_{no gate}', 'Interpreter', 'tex', ...
        'LabelVerticalAlignment', 'bottom', 'HandleVisibility', 'off');
    yline(ax, -sigma_raw, '--', 'Color', gray, 'LineWidth', 1.3, ...
        'Label', '-\sigma_{no gate}', 'Interpreter', 'tex', ...
        'LabelVerticalAlignment', 'top', 'HandleVisibility', 'off');

    % ±sigma gated
    yline(ax,  sigma_gated, ':', 'Color', dark, 'LineWidth', 1.6, ...
        'Label', '+\sigma_{gate}', 'Interpreter', 'tex', ...
        'LabelVerticalAlignment', 'bottom', 'HandleVisibility', 'off');
    yline(ax, -sigma_gated, ':', 'Color', dark, 'LineWidth', 1.6, ...
        'Label', '-\sigma_{gate}', 'Interpreter', 'tex', ...
        'LabelVerticalAlignment', 'top', 'HandleVisibility', 'off');

    xlabel(ax, 't  [s]', 'FontSize', 11);
    ylabel(ax, '\rho_{dot} error  [m/s]', 'Interpreter', 'tex', 'FontSize', 11);
    legend(ax, 'show', 'Location', 'best', 'Interpreter', 'tex');

    % Titolo riga 1
    annotation('textbox', [0 0.87 1 0.09], ...
        'String',  'RADAR  —  \rho_{dot} error  —  andamento temporale', ...
        'Interpreter',         'tex', ...
        'FontSize',            13, ...
        'FontWeight',          'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment',   'middle', ...
        'EdgeColor',           'none', ...
        'FitBoxToText',        'off');

    % Titolo riga 2
    annotation('textbox', [0 0.80 1 0.07], ...
        'String', sprintf('sigma no gate = %.4f m/s     sigma gate = %.4f m/s     gate pos < %.0f m', ...
            sigma_raw, sigma_gated, pos_thr), ...
        'Interpreter',         'none', ...
        'FontSize',            9, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment',   'middle', ...
        'EdgeColor',           'none', ...
        'FitBoxToText',        'off', ...
        'Color',               [0.35 0.35 0.35]);

end